---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-ingress
spec:
  interval: 10m
  timeout: 1m
  url: https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-test
  annotations:
    fluxcd.io/ignore: "false"
spec:
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
  install:
    remediation:
      retries: 30
  interval: 15s
  releaseName: nginx-test
  upgrade:
    remediation:
      retries: 30
  values:
    controller:
      service:
        type: LoadBalancer
